# Modified by joeroberts/terraform-aws-security-groups on 2026-08-12; see UPSTREAM.md.
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'terraform-aws-modules'
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set correct Node.js version
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Release
        uses: cycjimmy/semantic-release-action@ba330626c4750c19d8299de843f05c7aa5574f62 # v5 branch; tag v5.0.2
        with:
          semantic_version: 25.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
